"""empty message.

Revision ID: 4332a3eaa179
Revises: 4768b5a83ae5
Create Date: 2025-05-29 12:43:55.074255

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4332a3eaa179"
down_revision = "4768b5a83ae5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects", sa.Column("tracker_board_id", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "tracker_board_id")
    # ### end Alembic commands ###
