"""empty message.

Revision ID: 4768b5a83ae5
Revises: 748fe98de655
Create Date: 2025-05-29 11:18:25.213767

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4768b5a83ae5"
down_revision = "748fe98de655"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("automation_rules", "tracker_column_id")
    op.drop_column("automation_rules", "tracker_column_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "automation_rules",
        sa.Column(
            "tracker_column_name",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "automation_rules",
        sa.Column(
            "tracker_column_id",
            sa.VARCHAR(length=64),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
