"""empty message.

Revision ID: 9244601f7ae6
Revises: a672c85a0449
Create Date: 2025-04-26 11:04:24.556227

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9244601f7ae6"
down_revision = "a672c85a0449"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("gitlab_webhook_secret", sa.Text(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "gitlab_webhook_secret")
    # ### end Alembic commands ###
